// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cs_msgid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from cs_msgid.proto</summary>
  public static partial class CsMsgidReflection {

    #region Descriptor
    /// <summary>File descriptor for cs_msgid.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CsMsgidReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5jc19tc2dpZC5wcm90bxICcGIqhQkKDUMyU0xvZ2ljTXNnSWQSFwoTYzJz",
            "X2Jhc2VfbWluX21zZ19pZBAAEhcKE2Myc19iYXNlX21heF9tc2dfaWQQZBIe",
            "ChljMnNfYmFzZV9taW5fbG9naWNfbXNnX2lkEMgBEhkKFGMyc19oZWFydGJl",
            "YXRfcmVxX2lkEMkBEhkKFHMyY19oZWFydGJlYXRfcmVzX2lkEMoBEhsKFmMy",
            "c192ZXJpZnlfY29ubl9yZXFfaWQQ3QESIAobczJjX3ZlcmlmeV9jb25uX2Zh",
            "aWxfcmVzX2lkEN4BEh0KGHMyY19nZXRfcm9sZV9saXN0X250Zl9pZBDfARIb",
            "ChZjMnNfY3JlYXRlX3JvbGVfcmVxX2lkEOABEhsKFnMyY19jcmVhdGVfcm9s",
            "ZV9yZXNfaWQQ4QESGgoVYzJzX2dhbWVfbG9naW5fcmVxX2lkEOIBEhoKFXMy",
            "Y19nYW1lX2xvZ2luX3Jlc19pZBDjARIZChRjMnNfZXhpdF9nYW1lX3JlcV9p",
            "ZBDkARIZChRzMmNfZXhpdF9nYW1lX3Jlc19pZBDlARIaChVzMmNfc2VydmVy",
            "dGltZV9udGZfaWQQ5gESEwoOczJjX3RpcF9udGZfaWQQ5wESEgoNYzJzX2dt",
            "X3JlcV9pZBD7ARISCg1zMmNfZ21fcmVzX2lkEPwBEhsKFmMyc19jcmVhdGVf",
            "dGVhbV9yZXFfaWQQrAISGwoWczJjX2NyZWF0ZV90ZWFtX3Jlc19pZBCtAhIb",
            "ChZjMnNfaW52aXRlX3RlYW1fcmVxX2lkEK4CEiMKHnMyY19pbnZpdGVfdGVh",
            "bV9jb25maXJtX3JlcV9pZBCvAhIjCh5jMnNfaW52aXRlX3RlYW1fY29uZmly",
            "bV9yZXNfaWQQsAISFAoPczJjX3RlYW1fbnRmX2lkELECEhoKFWMyc19sZWF2",
            "ZV90ZWFtX3JlcV9pZBCyAhIbChZjMnNfc3RhcnRfbWF0Y2hfcmVxX2lkELMC",
            "EhwKF3MyY19yb29tX2NvbmZpcm1fcmVxX2lkELQCEhwKF2Myc19yb29tX2Nv",
            "bmZpcm1fcmVzX2lkELUCEh0KGHMyY19yZXN0YXJ0X21hdGNoX250Zl9pZBC2",
            "AhIaChVjMnNfc3RvcF9tYXRjaF9yZXFfaWQQtwISGwoWczJjX3Jvb21fbWVt",
            "YmVyX250Zl9pZBC4AhIXChJzMmNfcm9vbV9va19udGZfaWQQuQISJQogYzJz",
            "X3NlbGVjdF9tYXN0ZXJfaW5fcm9vbV9yZXFfaWQQugISIwoeYzJzX2xvY2tf",
            "bWFzdGVyX2luX3Jvb21fcmVxX2lkELsCEhgKE3MyY19zY2VuZV9va19udGZf",
            "aWQQvAISIwoeYzJzX2JhdHRsZV9sb2FkX3Byb2Nlc3NfcmVxX2lkEL0CEiMK",
            "HnMyY19iYXR0bGVfbG9hZF9wcm9jZXNzX250Zl9pZBC+AhIgChtzMmNfc2Nl",
            "bmVfdGVhbV9kYXRhc19udGZfaWQQvwISHgoZYzJzX2Jhc2VfbWF4X2xvZ2lj",
            "X21zZ19pZBDcC0ILWgkuLztjb25maWdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.C2SLogicMsgId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum C2SLogicMsgId {
    [pbr::OriginalName("c2s_base_min_msg_id")] C2SBaseMinMsgId = 0,
    [pbr::OriginalName("c2s_base_max_msg_id")] C2SBaseMaxMsgId = 100,
    [pbr::OriginalName("c2s_base_min_logic_msg_id")] C2SBaseMinLogicMsgId = 200,
    [pbr::OriginalName("c2s_heartbeat_req_id")] C2SHeartbeatReqId = 201,
    [pbr::OriginalName("s2c_heartbeat_res_id")] S2CHeartbeatResId = 202,
    [pbr::OriginalName("c2s_verify_conn_req_id")] C2SVerifyConnReqId = 221,
    [pbr::OriginalName("s2c_verify_conn_fail_res_id")] S2CVerifyConnFailResId = 222,
    [pbr::OriginalName("s2c_get_role_list_ntf_id")] S2CGetRoleListNtfId = 223,
    [pbr::OriginalName("c2s_create_role_req_id")] C2SCreateRoleReqId = 224,
    [pbr::OriginalName("s2c_create_role_res_id")] S2CCreateRoleResId = 225,
    [pbr::OriginalName("c2s_game_login_req_id")] C2SGameLoginReqId = 226,
    [pbr::OriginalName("s2c_game_login_res_id")] S2CGameLoginResId = 227,
    [pbr::OriginalName("c2s_exit_game_req_id")] C2SExitGameReqId = 228,
    [pbr::OriginalName("s2c_exit_game_res_id")] S2CExitGameResId = 229,
    [pbr::OriginalName("s2c_servertime_ntf_id")] S2CServertimeNtfId = 230,
    [pbr::OriginalName("s2c_tip_ntf_id")] S2CTipNtfId = 231,
    [pbr::OriginalName("c2s_gm_req_id")] C2SGmReqId = 251,
    [pbr::OriginalName("s2c_gm_res_id")] S2CGmResId = 252,
    [pbr::OriginalName("c2s_create_team_req_id")] C2SCreateTeamReqId = 300,
    [pbr::OriginalName("s2c_create_team_res_id")] S2CCreateTeamResId = 301,
    [pbr::OriginalName("c2s_invite_team_req_id")] C2SInviteTeamReqId = 302,
    [pbr::OriginalName("s2c_invite_team_confirm_req_id")] S2CInviteTeamConfirmReqId = 303,
    [pbr::OriginalName("c2s_invite_team_confirm_res_id")] C2SInviteTeamConfirmResId = 304,
    [pbr::OriginalName("s2c_team_ntf_id")] S2CTeamNtfId = 305,
    [pbr::OriginalName("c2s_leave_team_req_id")] C2SLeaveTeamReqId = 306,
    [pbr::OriginalName("c2s_start_match_req_id")] C2SStartMatchReqId = 307,
    [pbr::OriginalName("s2c_room_confirm_req_id")] S2CRoomConfirmReqId = 308,
    [pbr::OriginalName("c2s_room_confirm_res_id")] C2SRoomConfirmResId = 309,
    [pbr::OriginalName("s2c_restart_match_ntf_id")] S2CRestartMatchNtfId = 310,
    [pbr::OriginalName("c2s_stop_match_req_id")] C2SStopMatchReqId = 311,
    [pbr::OriginalName("s2c_room_member_ntf_id")] S2CRoomMemberNtfId = 312,
    [pbr::OriginalName("s2c_room_ok_ntf_id")] S2CRoomOkNtfId = 313,
    [pbr::OriginalName("c2s_select_master_in_room_req_id")] C2SSelectMasterInRoomReqId = 314,
    [pbr::OriginalName("c2s_lock_master_in_room_req_id")] C2SLockMasterInRoomReqId = 315,
    [pbr::OriginalName("s2c_scene_ok_ntf_id")] S2CSceneOkNtfId = 316,
    [pbr::OriginalName("c2s_battle_load_process_req_id")] C2SBattleLoadProcessReqId = 317,
    [pbr::OriginalName("s2c_battle_load_process_ntf_id")] S2CBattleLoadProcessNtfId = 318,
    [pbr::OriginalName("s2c_scene_team_datas_ntf_id")] S2CSceneTeamDatasNtfId = 319,
    [pbr::OriginalName("c2s_base_max_logic_msg_id")] C2SBaseMaxLogicMsgId = 1500,
  }

  #endregion

}

#endregion Designer generated code
